language: node_js
os: linux
node_js:
- lts/*
install:
- yarn install
script:
- yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist/
  target-branch: gh-pages
  github-token: $GITHUB_ACCESS_TOKEN
  keep_history: true
  on:
    branch: master